#ifndef BaseUGExports_symbian_H
#define BaseUGExports_symbian_H

// Shared library support
#define UGEXPORT __declspec(dllexport)
#define UGIMPORT __declspec(dllimport)

#define OGDCEXPORT __declspec(dllexport)
#define OGDCIMPORT __declspec(dllimport)

//为每个工程添加导入导出符

#ifdef BASE_EXPORTS
	#define BASE_API OGDCEXPORT
#else
	#define BASE_API OGDCIMPORT
#endif

#ifdef OGDC_EXPORTS
#define OGDC_API OGDCEXPORT
#else
#define OGDC_API OGDCIMPORT
#endif

#ifdef STREAM_EXPORTS
	#define STREAM_API UGEXPORT
	#define STREAM_APIC 
	#define STREAM_APIF UGEXPORT
#else
	#define STREAM_API UGIMPORT
	#define STREAM_APIC UGIMPORT
	#define STREAM_APIF 
#endif

#ifdef DATA_EXPORTS
#define DATA_API UGEXPORT
#define DATA_APIC 
#define DATA_APIF UGEXPORT
#else
#define DATA_API UGIMPORT
#define DATA_APIC UGIMPORT
#define DATA_APIF 
#endif

#ifdef  MAPPING_EXPORTS
#define MAPPING_API UGEXPORT
#define MAPPING_APIC 
#define MAPPING_APIF UGEXPORT
#else
#define MAPPING_API UGIMPORT
#define MAPPING_APIC UGIMPORT
#define MAPPING_APIF 
#endif

#ifdef TOOLKIT_EXPORTS
	#define TOOLKIT_API UGEXPORT
	#define TOOLKIT_APIC 
	#define TOOLKIT_APIF UGEXPORT
#else
	#define TOOLKIT_API UGIMPORT
	#define TOOLKIT_APIC UGIMPORT
	#define TOOLKIT_APIF 
#endif

#ifdef ELEMENT_EXPORTS
	#define ELEMENT_API OGDCEXPORT
	#define ELEMENT_APIC 
	#define ELEMENT_APIF OGDCEXPORT
#else
	#define ELEMENT_API OGDCIMPORT
	#define ELEMENT_APIC OGDCIMPORT
	#define ELEMENT_APIF 
#endif


#ifdef NETTOOLKIT_EXPORTS
	#define NETTOOLKIT_API UGEXPORT
#else
	#define NETTOOLKIT_API UGIMPORT
#endif

#ifdef BASE3D_EXPORTS
	#define BASE3D_API UGEXPORT
#else
	#define BASE3D_API UGIMPORT
#endif

#ifdef ALGORITHM_EXPORTS
	#define ALGORITHM_API UGEXPORT
#else
	#define ALGORITHM_API UGIMPORT
#endif

#ifdef COMPOUNDFILE_EXPORTS
	#define COMPOUNDFILE_API UGEXPORT
#else
	#define COMPOUNDFILE_API UGIMPORT
#endif

#ifdef CACHEBUILDER_EXPORTS
	#define CACHEBUILDER_API UGEXPORT
#else
	#define CACHEBUILDER_API UGIMPORT
#endif

#ifdef DATAEXCHANGE_EXPORTS
	#define DATAEXCHANGE_API UGEXPORT
#else
	#define DATAEXCHANGE_API UGIMPORT
#endif

#ifdef DATASETOPERATION_EXPORTS
	#define DATASETOPERATION_API UGEXPORT
#else
	#define DATASETOPERATION_API UGIMPORT
#endif

#ifdef SYMBOLEXCHANGE_EXPORTS
	#define SYMBOLEXCHANGE_API UGEXPORT
#else
	#define SYMBOLEXCHANGE_API UGIMPORT
#endif

#ifdef DRAWING_EXPORTS
	#define DRAWING_API UGEXPORT
	#define DRAWING_APIC
	#define DRAWING_APIF UGEXPORT	
#else
	#define DRAWING_API UGIMPORT
	#define DRAWING_APIC UGIMPORT
	#define DRAWING_APIF
#endif

#ifdef DRAWINGCAD_EXPORTS
	#define DRAWINGCAD_API UGEXPORT
#else
	#define DRAWINGCAD_API UGIMPORT
#endif

#ifdef FILEPARSERMAPGIS_EXPORTS
#define FILEPARSERMAPGIS_API UGEXPORT
#else
#define FILEPARSERMAPGIS_API UGIMPORT
#endif

#ifdef DRAWING3D_EXPORTS
	#define DRAWING3D_API UGEXPORT
#else
	#define DRAWING3D_API UGIMPORT
#endif

#ifdef DRAWINGLAYOUT_EXPORTS
	#define DRAWINGLAYOUT_API UGEXPORT
#else
	#define DRAWINGLAYOUT_API UGIMPORT
#endif

#ifdef MAPEDITOR_EXPORTS
	#define MAPEDITOR_API UGEXPORT
#else
	#define MAPEDITOR_API UGIMPORT
#endif

#ifdef ENGINE_EXPORTS
	#define ENGINE_API UGEXPORT
	#define ENGINE_APIC 
	#define ENGINE_APIF UGEXPORT
#else
	#define ENGINE_API UGIMPORT
	#define ENGINE_APIC UGIMPORT
	#define ENGINE_APIF 
#endif

#ifdef ENGINEOGDC_EXPORTS
	#define ENGINEOGDC_API UGEXPORT
#else
	#define ENGINEOGDC_API UGIMPORT
#endif

#ifdef ENGINEEXTENDFILE_EXPORTS
	#define ENGINEEXTENDFILE_API UGEXPORT
#else
	#define ENGINEEXTENDFILE_API UGIMPORT
#endif

#ifdef ENGINEIMAGEPLUGIN_EXPORTS
	#define ENGINEIMAGEPLUGIN_API UGEXPORT
#else
	#define ENGINEIMAGEPLUGIN_API UGIMPORT
#endif

#ifdef ENGINEMYSQL_EXPORTS
	#define ENGINEMYSQL_API UGEXPORT
#else
	#define ENGINEMYSQL_API UGIMPORT
#endif

#ifdef ENTERPRISEENGINE_EXPORTS
	#define ENTERPRISEENGINE_API UGEXPORT
#else
	#define ENTERPRISEENGINE_API UGIMPORT
#endif

#ifdef PLUGINSIT_EXPORTS
	#define PLUGINSIT_API UGEXPORT
#else
	#define PLUGINSIT_API UGIMPORT
#endif

#ifdef PLUGINGDAL_EXPORTS
	#define PLUGINGDAL_API UGEXPORT
#else
	#define PLUGINGDAL_API UGIMPORT
#endif

#ifdef PLUGINMAPCACHE_EXPORTS
	#define PLUGINMAPCACHE_API UGEXPORT
#else
	#define PLUGINMAPCACHE_API UGIMPORT
#endif

#ifdef FILEPARSER_EXPORTS
#define FILEPARSER_API UGEXPORT
#else
#define FILEPARSER_API UGIMPORT
#endif

#ifdef FILEPARSERHFA_EXPORTS
#define FILEPARSERHFA_API UGEXPORT
#else
#define FILEPARSERHFA_API UGIMPORT
#endif

#ifdef FILEPARSERRAW_EXPORTS
#define FILEPARSERRAW_API UGEXPORT
#else
#define FILEPARSERRAW_API UGIMPORT
#endif

#ifdef FILEPARSERSHAPE_EXPORTS
	#define FILEPARSERSHAPE_API UGEXPORT
#else
	#define FILEPARSERSHAPE_API UGIMPORT
#endif

#ifdef FILEPARSERGRID_EXPORTS
	#define FILEPARSERGRID_API UGEXPORT
#else
	#define FILEPARSERGRID_API UGIMPORT
#endif

#ifdef FILEPARSERACAD_EXPORTS
	#define FILEPARSERACAD_API UGEXPORT
#else
	#define FILEPARSERACAD_API UGIMPORT
#endif

#ifdef GEOMETRY_EXPORTS
	#define GEOMETRY_API UGEXPORT
	#define GEOMETRY_APIC 
	#define GEOMETRY_APIF UGEXPORT
#else
	#define GEOMETRY_API UGIMPORT
	#define GEOMETRY_APIC UGIMPORT
	#define GEOMETRY_APIF 
#endif

#ifdef GEOMETRY3D_EXPORTS
	#define GEOMETRY3D_API UGEXPORT
#else
	#define GEOMETRY3D_API UGIMPORT
#endif

#ifdef GEOMETRYCAD_EXPORTS
	#define GEOMETRYCAD_API UGEXPORT
#else
	#define GEOMETRYCAD_API UGIMPORT
#endif

#ifdef GEOMETRYLAYOUT_EXPORTS
	#define GEOMETRYLAYOUT_API UGEXPORT
#else
	#define GEOMETRYLAYOUT_API UGIMPORT
#endif

#ifdef GEOMETRY3D_EXPORTS
	#define GEOMETRY3D_API UGEXPORT
#else
	#define GEOMETRY3D_API UGIMPORT
#endif

#ifdef GEOOPERATION_EXPORTS
	#define GEOOPERATION_API UGEXPORT
#else
	#define GEOOPERATION_API UGIMPORT
#endif

#ifdef GRAPHICS_EXPORTS
	#define GRAPHICS_API UGEXPORT
	#define GRAPHICS_APIC 
	#define GRAPHICS_APIF UGEXPORT
#else
	#define GRAPHICS_API UGIMPORT
	#define GRAPHICS_APIC UGIMPORT
	#define GRAPHICS_APIF 
#endif

#ifdef RECTIFY_EXPORTS
	#define RECTIFY_API UGEXPORT
#else
	#define RECTIFY_API UGIMPORT
#endif

#ifdef SHEETJOIN_EXPORTS
	#define SHEETJOIN_API UGEXPORT
#else
	#define SHEETJOIN_API UGIMPORT
#endif

#ifdef IMAGEANALYST_EXPORTS
	#define IMAGEANALYST_API UGEXPORT
#else
	#define IMAGEANALYST_API UGIMPORT
#endif

#ifdef GRIDANALYST_EXPORTS
	#define GRIDANALYST_API UGEXPORT
#else
	#define GRIDANALYST_API UGIMPORT
#endif

#ifdef GRIDMODELING_EXPORTS
#define GRIDMODELING_API UGEXPORT
#else
#define GRIDMODELING_API UGIMPORT
#endif

#ifdef LAYOUT_EXPORTS
	#define LAYOUT_API UGEXPORT
#else
	#define LAYOUT_API UGIMPORT
#endif

#ifdef LAYOUTEDITOR_EXPORTS
	#define LAYOUTEDITOR_API UGEXPORT
#else
	#define LAYOUTEDITOR_API UGIMPORT
#endif

#ifdef LICENSE_EXPORTS
	#define LICENSE_API UGEXPORT
#else
	#define LICENSE_API UGIMPORT
#endif

#ifdef MAP_EXPORTS
	#define MAP_API UGEXPORT
	#define MAP_APIC
	#define MAP_APIF UGEXPORT
#else
	#define MAP_API UGIMPORT
	#define MAP_APIC UGIMPORT
	#define MAP_APIF
#endif

#ifdef MAPWINDOW_EXPORTS
	#define MAPWINDOW_API UGEXPORT
#else
	#define MAPWINDOW_API UGIMPORT
#endif

#ifdef MAPBORDER_EXPORTS
	#define MAPBORDER_API UGEXPORT
#else
	#define MAPBORDER_API UGIMPORT
#endif

#ifdef THEMEBASE_EXPORTS
	#define THEMEBASE_API UGEXPORT
	#define THEMEBASE_APIC 
	#define THEMEBASE_APIF UGEXPORT
#else
	#define THEMEBASE_API UGIMPORT
	#define THEMEBASE_APIC UGIMPORT
	#define THEMEBASE_APIF
#endif

#ifdef THEMEADVANCE_EXPORTS
	#define THEMEADVANCE_API UGEXPORT
	#define THEMEADVANCE_APIC 
	#define THEMEADVANCE_APIF UGEXPORT
#else
	#define THEMEADVANCE_API UGIMPORT
	#define THEMEADVANCE_APIC UGIMPORT
	#define THEMEADVANCE_APIF
#endif

#ifdef THEME3DBASE_EXPORTS
	#define THEME3DBASE_API UGEXPORT
#else
	#define THEME3DBASE_API UGIMPORT
#endif

#ifdef METADATA_EXPORTS
#define METADATA_API UGEXPORT
#else
#define METADATA_API UGIMPORT
#endif

#ifdef NETWORKBUILDER_EXPORTS
	#define NETWORKBUILDER_API UGEXPORT
#else
	#define NETWORKBUILDER_API UGIMPORT
#endif

#ifdef NETWORKENVIRONMENT_EXPORTS
	#define NETWORKENVIRONMENT_API UGEXPORT
#else
	#define NETWORKENVIRONMENT_API UGIMPORT
#endif

#ifdef GEOMETRICNETWORK_EXPORTS
#define GEOMETRICNETWORK_API UGEXPORT
#else
#define GEOMETRICNETWORK_API UGIMPORT
#endif

#ifdef PUBLICTRANSPORT_EXPORTS
#define PUBLICTRANSPORT_API UGEXPORT
#else
#define PUBLICTRANSPORT_API UGIMPORT
#endif

#ifdef PATHANALYST_EXPORTS
	#define PATHANALYST_API UGEXPORT
#else
	#define PATHANALYST_API UGIMPORT
#endif

#ifdef LOGISTICS_EXPORTS
	#define LOGISTICS_API UGEXPORT
#else
	#define LOGISTICS_API UGIMPORT
#endif

#ifdef ALLOCATION_EXPORTS
	#define ALLOCATION_API UGEXPORT
#else
	#define ALLOCATION_API UGIMPORT
#endif

#ifdef NETWORKANALYST_EXPORTS
	#define NETWORKANALYST_API UGEXPORT
#else
	#define NETWORKANALYST_API UGIMPORT
#endif

#ifdef GEOCODE_EXPORTS
	#define GEOCODE_API UGEXPORT
#else
	#define GEOCODE_API UGIMPORT
#endif

#ifdef OPERATION_EXPORTS
#define OPERATION_API UGEXPORT
#else
#define OPERATION_API UGIMPORT
#endif

#ifdef OVERLAY_EXPORTS
#define OVERLAY_API UGEXPORT
#else
#define OVERLAY_API UGIMPORT
#endif

#ifdef PROXIMITY_EXPORTS
#define PROXIMITY_API UGEXPORT
#else
#define PROXIMITY_API UGIMPORT
#endif

#ifdef GENERALIZATION_EXPORTS
#define GENERALIZATION_API UGEXPORT
#else
#define GENERALIZATION_API UGIMPORT
#endif

#ifdef ENGINESDBPLUS_EXPORTS
	#define SDBPLUSENGINE_API UGEXPORT
#else
	#define SDBPLUSENGINE_API UGIMPORT
#endif


#ifdef ORCENGINE_EXPORTS
	#define ORCENGINE_API UGEXPORT
#else
	#define ORCENGINE_API UGIMPORT
#endif

#ifdef ENGINEPG_EXPORTS
	#define ENGINEPG_API UGEXPORT
#else
	#define ENGINEPG_API UGIMPORT
#endif

#ifdef UDBENGINE_EXPORTS
	#define UDBENGINE_API UGEXPORT
	#define UDBENGINE_APIC 
	#define UDBENGINE_APIF UGEXPORT
#else
	#define UDBENGINE_API UGIMPORT
	#define UDBENGINE_APIC UGIMPORT
	#define UDBENGINE_APIF 
#endif

#ifdef PROJECTION_EXPORTS
	#define PROJECTION_API UGEXPORT
	#define PROJECTION_APIC 
	#define PROJECTION_APIF UGEXPORT
#else
	#define PROJECTION_API UGIMPORT
	#define PROJECTION_APIC UGIMPORT
	#define PROJECTION_APIF 
#endif

#ifdef ENGINEOGC_EXPORTS
	#define ENGINEOGC_API UGEXPORT
#else
	#define ENGINEOGC_API UGIMPORT
#endif

#ifdef OGCPARSER_EXPORTS
#define OGCPARSER_API UGEXPORT
#else
#define OGCPARSER_API UGIMPORT
#endif

#ifdef INFORMIXENGINE_EXPORTS
#define INFORMIXENGINE_API UGEXPORT
#else
#define INFORMIXENGINE_API UGIMPORT
#endif

#ifdef SYMBOL_EXPORTS
	#define SYMBOL_API UGEXPORT
	#define SYMBOL_APIC 
	#define SYMBOL_APIF UGEXPORT
#else
	#define SYMBOL_API UGIMPORT
	#define SYMBOL_APIC UGIMPORT
	#define SYMBOL_APIF 
#endif

#ifdef SYMBOLMARKER_EXPORTS
	#define SYMBOLMARKER_API UGEXPORT
	#define SYMBOLMARKER_APIC 
	#define SYMBOLMARKER_APIF UGEXPORT
#else
	#define SYMBOLMARKER_API UGIMPORT
	#define SYMBOLMARKER_APIC UGIMPORT
	#define SYMBOLMARKER_APIF
#endif

#ifdef SYMBOLMARKER3D_EXPORTS
	#define SYMBOLMARKER3D_API UGEXPORT
#else
	#define SYMBOLMARKER3D_API UGIMPORT
#endif

#ifdef SYMBOLLINE_EXPORTS
	#define SYMBOLLINE_API UGEXPORT
	#define SYMBOLLINE_APIC 
	#define SYMBOLLINE_APIF UGEXPORT
#else
	#define SYMBOLLINE_API UGIMPORT
	#define SYMBOLLINE_APIC UGIMPORT
	#define SYMBOLLINE_APIF
#endif

#ifdef SYMBOLFILL_EXPORTS
	#define SYMBOLFILL_API UGEXPORT
	#define SYMBOLFILL_APIC 
	#define SYMBOLFILL_APIF UGEXPORT
#else
	#define SYMBOLFILL_API UGIMPORT
	#define SYMBOLFILL_APIC UGIMPORT
	#define SYMBOLFILL_APIF
#endif

#ifdef SYMBOLRULE_EXPORTS
	#define SYMBOLRULE_API UGEXPORT
#else
	#define SYMBOLRULE_API UGIMPORT
#endif

#ifdef TABLE_EXPORTS
	#define TABLE_API UGEXPORT
#else
	#define TABLE_API UGIMPORT
#endif

#ifdef SQLITECI_EXPORTS
	#define SQLITECI_API UGEXPORT
#else
	#define SQLITECI_API UGIMPORT
#endif

#ifdef MYSQLCI_EXPORTS
	#define MYSQLCI_API UGEXPORT
#else
	#define MYSQLCI_API UGIMPORT
#endif

#ifdef PGSQLCI_EXPORTS
	#define PGSQLCI_API	UGEXPORT
#else
	#define PGSQLCI_API	UGIMPORT
#endif

#ifdef ORACLECI_EXPORTS
	#define ORACLECI_API UGEXPORT
#else
	#define ORACLECI_API UGIMPORT
#endif

#ifdef ODBCCI_EXPORTS
	#define ODBCCI_API UGEXPORT
#else
	#define ODBCCI_API UGIMPORT
#endif

#ifdef TOPOLOGY_EXPORTS
#define TOPOLOGY_API UGEXPORT
#else
#define TOPOLOGY_API UGIMPORT
#endif

#ifdef DATACHECK_EXPORTS
#define DATACHECK_API UGEXPORT
#else
#define DATACHECK_API UGIMPORT
#endif

#ifdef TOPOBASE_EXPORTS
	#define TOPOBASE_API UGEXPORT
#else
	#define TOPOBASE_API UGIMPORT
#endif

#ifdef TOPOBUILDER_EXPORTS
	#define TOPOBUILDER_API UGEXPORT
#else
	#define TOPOBUILDER_API UGIMPORT
#endif

#ifdef SPATIALQUERY_EXPORTS
#define SPATIALQUERY_API UGEXPORT
#else
#define SPATIALQUERY_API UGIMPORT
#endif

#ifdef GRAPHICSU_EXPORTS
	#define GRAPHICSU_API UGEXPORT
#else
	#define GRAPHICSU_API UGIMPORT
#endif

#ifdef GRAPHICSW_EXPORTS
	#define GRAPHICSW_API UGEXPORT
#else
	#define GRAPHICSW_API UGIMPORT
#endif

#ifdef GRAPHICSPDF_EXPORTS
	#define GRAPHICSPDF_API UGEXPORT
#else
	#define GRAPHICSPDF_API UGIMPORT
#endif

//star Add tangzq in 20081-12-19
#ifdef GRAPHICSXPS_EXPORTS
#define GRAPHICSXPS_API UGEXPORT
#else
#define GRAPHICSXPS_API UGIMPORT
#endif
//end Add tangzq in 20081-12-19

#ifdef GRAPHICSQT_EXPORTS
	#define GRAPHICSQT_API UGEXPORT
#else
	#define GRAPHICSQT_API UGIMPORT
#endif

#ifdef GRAPHICSMINIGUI_EXPORTS
	#define GRAPHICSMINIGUI_API UGEXPORT
#else
	#define GRAPHICSMINIGUI_API UGIMPORT
#endif

#ifdef GRAPHICSPS_EXPORTS
	#define GRAPHICSPS_API UGEXPORT
#else
	#define GRAPHICSPS_API UGIMPORT
#endif

#ifdef GRAPHICSMEM_EXPORTS
	#define GRAPHICSMEM_API UGEXPORT
	#define GRAPHICSMEM_APIC 
	#define GRAPHICSMEM_APIF UGEXPORT
#else
	#define GRAPHICSMEM_API UGIMPORT
	#define GRAPHICSMEM_APIC UGIMPORT
	#define GRAPHICSMEM_APIF 
#endif

#ifdef WORKSPACE_EXPORTS
	#define WORKSPACE_API UGEXPORT
#else
	#define WORKSPACE_API UGIMPORT
#endif

#ifdef GRAPHICSX_EXPORTS
	#define GRAPHICSX_API UGEXPORT
#else
	#define GRAPHICSX_API UGIMPORT
#endif

//3D-related projects
#ifdef DRAWING3D_EXPORTS
#define DRAWING3D_API UGEXPORT
#else
#define DRAWING3D_API UGIMPORT
#endif

#ifdef EDITOR3D_EXPORTS
#define EDITOR3D_API UGEXPORT
#else
#define EDITOR3D_API UGIMPORT
#endif

#ifdef SYMBOL3D_EXPORTS
#define SYMBOL3D_API UGEXPORT
#else
#define SYMBOL3D_API UGIMPORT
#endif

#ifdef GRAPHICS3D_EXPORTS
#define GRAPHICS3D_API UGEXPORT
#else 
#define GRAPHICS3D_API UGIMPORT 
#endif

#ifdef GRAPHICS3DGL_EXPORTS
#define GRAPHICS3DGL_API UGEXPORT
#else 
#define GRAPHICS3DGL_API UGIMPORT 
#endif

#ifdef GRAPHICS3DDX_EXPORTS
#define GRAPHICS3DDX_API UGEXPORT
#else 
#define GRAPHICS3DDX_API UGIMPORT 
#endif

#ifdef RENDER_EXPORTS
#define RENDER_API UGEXPORT
#else 
#define RENDER_API UGIMPORT 
#endif

#ifdef SCENE_EXPORTS
#define SCENE_API UGEXPORT
#else 
#define SCENE_API UGIMPORT 
#endif

#ifdef SCENEEDITOR_EXPORTS
#define SCENEEDITOR_API UGEXPORT
#else 
#define SCENEEDITOR_API UGIMPORT 
#endif

#ifdef LAYER3DDATASET_EXPORTS
#define LAYER3DDATASET_API UGEXPORT
#else 
#define LAYER3DDATASET_API UGIMPORT 
#endif

#ifdef LAYER3DFILE_EXPORTS
#define LAYER3DFILE_API UGEXPORT
#else 
#define LAYER3DFILE_API UGIMPORT 
#endif

#ifdef LAYER3DTREE_EXPORTS
#define LAYER3DTREE_API UGEXPORT
#else 
#define LAYER3DTREE_API UGIMPORT 
#endif

#ifdef LAYERGEIMAGE_EXPORTS
#define LAYERGEIMAGE_API UGEXPORT
#else 
#define LAYERGEIMAGE_API UGIMPORT 
#endif

#ifdef SDEENGINE_EXPORTS
	#define SDEENGINE_API UGEXPORT
#else
	#define SDEENGINE_API UGIMPORT
#endif


#ifdef DB2ENGINE_EXPORTS
#define DB2ENGINE_API UGEXPORT
#else
#define DB2ENGINE_API UGIMPORT
#endif

#ifdef SQLENGINE_EXPORTS
#define SQLENGINE_API UGEXPORT
#else
#define SQLENGINE_API UGIMPORT
#endif

#ifdef KINGENGINE_EXPORTS
#define KINGENGINE_API UGEXPORT
#else
#define KINGENGINE_API UGIMPORT
#endif

#ifdef MEMENGINE_EXPORTS
#define MEMENGINE_API UGEXPORT
#else
#define MEMENGINE_API UGIMPORT
#endif

#ifdef BUILDER3D_EXPORTS
#define BUILDER3D_API UGEXPORT
#else
#define BUILDER3D_API UGIMPORT
#endif

#ifdef SPATIALINDEX_EXPORTS
#define SPATIALINDEX_API UGEXPORT
#else
#define SPATIALINDEX_API UGIMPORT
#endif

#ifdef FILEPARSEROGR_EXPORTS
#define FILEPARSEROGR_API UGEXPORT
#else
#define FILEPARSEROGR_API UGIMPORT
#endif

#ifdef FILEPARSERGDAL_EXPORTS
#define FILEPARSERGDAL_API UGEXPORT
#else
#define FILEPARSERGDAL_API UGIMPORT
#endif

#ifdef FILEPARSERMDB_EXPORTS
#define FILEPARSERMDB_API UGEXPORT
#else
#define FILEPARSERMDB_API UGIMPORT
#endif

#ifdef FILEPARSERGTIFF_EXPORTS
	#define FILEPARSERGTIFF_API UGEXPORT
#else
	#define FILEPARSERGTIFF_API UGIMPORT
#endif

#ifdef FILEPARSERMITAB_EXPORTS
#define FILEPARSERMITAB_API UGEXPORT
#else
#define FILEPARSERMITAB_API UGIMPORT
#endif

#ifdef FILEPARSERENC_EXPORTS
#define FILEPARSERENC_API UGEXPORT
#else
#define FILEPARSERENC_API UGIMPORT
#endif

#ifdef  FILEPARSERTEMS_EXPORTS
#define FILEPARSERTEMS_API UGEXPORT
#else
#define FILEPARSERTEMS_API UGIMPORT
#endif

#ifdef FILEPARSERKML_EXPORTS
#define FILEPARSERKML_API UGEXPORT
#else
#define FILEPARSERKML_API UGIMPORT
#endif

#ifdef MAPWINDOW_EXPORTS
#define MAPWINDOW_API UGEXPORT
#else
#define MAPWINDOW_API UGIMPORT
#endif

#ifdef MAPEDITOR_EXPORTS
#define MAPEDITOR_API UGEXPORT
#else
#define MAPEDITOR_API UGIMPORT
#endif

#ifdef REPRESENTATION_EXPORTS
#define REPRESENTATION_API UGEXPORT
#else
#define REPRESENTATION_API UGIMPORT
#endif

#ifdef DB2CI_EXPORTS
#define DB2CI_API UGEXPORT
#else
#define DB2CI_API UGIMPORT
#endif

#ifdef INFORMIXCI_EXPORTS
#define INFORMIXCI_API UGEXPORT
#else
#define INFORMIXCI_API UGIMPORT
#endif

#ifdef COMPOUNDFILE64_EXPORTS
#define COMPOUNDFILE64_API UGEXPORT
#else
#define COMPOUNDFILE64_API UGIMPORT
#endif

#ifdef ENGINEUDB_EXPORTS
#define ENGINEUDB_API UGEXPORT
#else
#define ENGINEUDB_API UGIMPORT
#endif

#ifdef ENGINEINFORMIX_EXPORTS
#define ENGINEINFORMIX_API UGEXPORT
#else
#define ENGINEINFORMIX_API UGIMPORT
#endif

#ifdef KMLGENERATOR_EXPORTS
#define KMLGENERATOR_API UGEXPORT
#else
#define KMLGENERATOR_API UGIMPORT
#endif

#ifdef INTERNATIONALICU_EXPORTS
#define INTERNATIONALICU_API UGEXPORT
#else
#define INTERNATIONALICU_API UGIMPORT
#endif

#ifdef PLUGINGLOBALCACHE_EXPORTS
#define PLUGINGLOBALCACHE_API UGEXPORT
#else
#define PLUGINGLOBALCACHE_API UGIMPORT
#endif

#ifdef PLUGINGECACHE_EXPORTS
#define PLUGINGECACHE_API UGEXPORT
#else
#define PLUGINGECACHE_API UGIMPORT
#endif

#ifdef REMOTESENSINGANALYST_EXPORTS
#define REMOTESENSINGANALYST_API UGEXPORT
#else
#define REMOTESENSINGANALYST_API UGIMPORT
#endif

#ifdef LAYER3DMAP_EXPORTS
#define LAYER3DMAP_API UGEXPORT
#else
#define LAYER3DMAP_API UGIMPORT
#endif

#ifdef PROCESSMODELING_EXPORTS
#define PROCESSMODELING_API UGEXPORT
#else
#define PROCESSMODELING_API UGIMPORT
#endif

#ifdef FILEPARSERCOMMON_EXPORTS
#define FILEPARSERCOMMON_API UGEXPORT
#else
#define FILEPARSERCOMMON_API UGIMPORT
#endif

#ifdef PLUGINCOMMON_EXPORTS
#define PLUGINCOMMON_API UGEXPORT
#else
#define PLUGINCOMMON_API UGIMPORT
#endif


//  [added by zhangshuo at 1/12/2010]
#ifdef ENGINENETCDF_EXPORTS
#define ENGINENETCDF_API UGEXPORT
#else
#define ENGINENETCDF_API UGIMPORT
#endif
//  [added by zhangshuo at 1/12/2010]

//  [added by zengwh at 4/13/2010]
#ifdef UNIVERSALCI_EXPORTS
#define UNIVERSALCI_API UGEXPORT
#else
#define UNIVERSALCI_API UGIMPORT
#endif

#ifdef UODBCCI_EXPORTS
#define UODBCCI_API UGEXPORT
#else
#define UODBCCI_API UGIMPORT
#endif

#ifdef UORACLECI_EXPORTS
#define UORACLECI_API UGEXPORT
#else
#define UORACLECI_API UGIMPORT
#endif
//  [added by zengwh at 4/13/2010]

//  [added by zengwh at 6/11/2010]
#ifdef DATARECOVERY_EXPORTS
#define DATARECOVERY_API UGEXPORT
#else
#define DATARECOVERY_API UGIMPORT
#endif
//  [added by zengwh at 6/11/2010]

#ifdef GRAPHICSMEM_EXPORTS
#define GRAPHICSMEM_API UGEXPORT
#else
#define GRAPHICSMEM_API UGIMPORT
#endif

#endif


